# Generated by Django 2.2.5 on 2019-09-15 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190915_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='orghost',
        ),
    ]
